from pathlib import Path
import re

from flat_ch.core.domain import FlatFact
from flat_ch.core.operators import Arity, Operator
from flat_ch.core.types import Type

HEADER_RULE = "%% ============================================================================="

BASE_DIR = Path(__file__).resolve().parent
SRC_DIR = BASE_DIR / "encodings"
TEMPLATE_DIR = SRC_DIR / "templates"
GENERATED_DIR = SRC_DIR / "generated"

_TEMPLATE_EXPANSIONS = {
    "mixed_numeric_pairs": [
        {
            "LEFT_TYPE": "_fch_type_int_id",
            "RIGHT_TYPE": "_fch_type_float_id",
        },
        {
            "LEFT_TYPE": "_fch_type_float_id",
            "RIGHT_TYPE": "_fch_type_int_id",
        },
    ],
    "float_numeric_pairs": [
        {
            "LEFT_TYPE": "_fch_type_int_id",
            "RIGHT_TYPE": "_fch_type_float_id",
        },
        {
            "LEFT_TYPE": "_fch_type_float_id",
            "RIGHT_TYPE": "_fch_type_int_id",
        },
        {
            "LEFT_TYPE": "_fch_type_float_id",
            "RIGHT_TYPE": "_fch_type_float_id",
        },
    ],
}

_EXPAND_DIRECTIVE = re.compile(r"^%\s*@expand\s+(\w+)\s*$")
_END_EXPAND_DIRECTIVE = re.compile(r"^%\s*@endexpand\s*$")

def generate_files() -> None:
    if not TEMPLATE_DIR.exists():
        print(f"Error: Template directory not found at: '{TEMPLATE_DIR}'")
        return

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    template_files = sorted(TEMPLATE_DIR.glob("*.lp"))

    if not template_files:
        print(f"No template files (.lp) detected in '{TEMPLATE_DIR}'")
        return

    generated_files = {
        "constants.lp": _generate_constants,
        "flatten.lp": _generate_flatten,
        "output.lp": _generate_output,
    }
    for template_path in template_files:
        base_name = template_path.stem
        generated_files[f"{base_name}.lp"] = (lambda path=template_path: _generate_from_template(path))

    for file_name, generator_func in generated_files.items():
        lines = generator_func()
        _finish_file(file_name, lines)

def _finish_file(file_name: str, lines: list[str]) -> None:
    file_path = GENERATED_DIR / file_name
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    
    print(f"[INFO] Successfully generated file at: {file_path}")

def _build_header(*content: str) -> list[str]:
    lines = [
        HEADER_RULE,
        "%% THIS FILE WAS AUTOMATICALLY GENERATED BY --generate",
        "%% DO NOT EDIT THIS FILE MANUALLY",
    ]

    if content:
        lines.append("%%")
        lines.extend(f"%% {line}" if line else "%%" for line in content)

    lines.extend([HEADER_RULE, ""])
    return lines

def _generate_constants() -> list[str]:
    lines = []
    lines.extend(_build_header())
    lines.append("%% --- Type Constants ---")
    for t in Type:
        lines.append(f"#const _fch_type_{t.name.lower()}_id = {t.value}.")

    lines.extend(["", "%% --- Operator Constants ---"])
    for op in Operator:
        lines.append(f"#const _fch_op_{op.asp_name}_id = {op.value}.")

    return lines

def _generate_from_template(template_path: Path) -> list[str]:
    raw_content = template_path.read_text(encoding="utf-8")
    raw_content = _expand_template_blocks(raw_content)

    static_body = raw_content.replace("_fch_template", "_fch_static")
    dynamic_body = raw_content.replace("_fch_template", "_fch_dynamic")

    lines = _build_header(
        "Generated from a template file.",
        f"Generated from: encodings/templates/{template_path.name}",
        "Contains: static and dynamic variants.",
    )
    lines.extend([
        "%% STATIC",
        static_body,
        "",
        "%% DYNAMIC",
        dynamic_body,
    ])

    return lines


def _expand_template_blocks(raw_content: str) -> str:
    lines = raw_content.splitlines()
    expanded_lines: list[str] = []
    index = 0

    while index < len(lines):
        match = _EXPAND_DIRECTIVE.match(lines[index])
        if not match:
            expanded_lines.append(lines[index])
            index += 1
            continue

        expansion_name = match.group(1)
        variants = _TEMPLATE_EXPANSIONS.get(expansion_name)
        if variants is None:
            raise ValueError(f"Unknown template expansion: {expansion_name}")

        block_lines: list[str] = []
        index += 1
        while index < len(lines) and not _END_EXPAND_DIRECTIVE.match(lines[index]):
            block_lines.append(lines[index])
            index += 1

        if index >= len(lines):
            raise ValueError(f"Unterminated template expansion block: {expansion_name}")

        block = "\n".join(block_lines)
        for variant_index, variant in enumerate(variants):
            rendered = block
            for key, value in variant.items():
                rendered = rendered.replace(f"{{{{{key}}}}}", value)

            expanded_lines.extend(rendered.splitlines())
            if variant_index != len(variants) - 1 and rendered:
                expanded_lines.append("")

        index += 1

    return "\n".join(expanded_lines)

def _generate_flatten() -> list[str]:
    lines = []
    lines.extend(_build_header("Generated from FlatFact and Operator metadata."))
    lines.append("%% CORE ELEMENTS")

    for fact in FlatFact:
        vars_str = ", ".join(fact.variables)
        lines.append(f"_fch_{fact.value}({vars_str}) :- _fch_flat({fact.value}({vars_str})).")

    lines.extend(["", "%% OPERATIONS"])

    lazy_ops = {"if", "ite"}

    for op in Operator:
        op_name = op.asp_name
        allowed = op.allowed_arities

        if allowed & Arity.UNARY:
            lines.append(f"_fch_op_{op_name}(ID, ARG_1_ID) :- _fch_flat(op_{op_name}(ID, ARG_1_ID)).")
            if op_name not in lazy_ops:
                lines.append(f"_fch_op_strict_child(ID, ARG_1_ID) :- _fch_op_{op_name}(ID, ARG_1_ID).")
        if allowed & Arity.BINARY:
            lines.append(f"_fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID) :- _fch_flat(op_{op_name}(ID, ARG_1_ID, ARG_2_ID)).")
            if op_name not in lazy_ops:
                lines.append(f"_fch_op_strict_child(ID, ARG_1_ID) :- _fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID).")
                lines.append(f"_fch_op_strict_child(ID, ARG_2_ID) :- _fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID).")
            
        if allowed & Arity.TERNARY:
            lines.append(f"_fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID, ARG_3_ID) :- _fch_flat(op_{op_name}(ID, ARG_1_ID, ARG_2_ID, ARG_3_ID)).")
            if op_name not in lazy_ops:
                lines.append(f"_fch_op_strict_child(ID, ARG_1_ID) :- _fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID, ARG_3_ID).")
                lines.append(f"_fch_op_strict_child(ID, ARG_2_ID) :- _fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID, ARG_3_ID).")
                lines.append(f"_fch_op_strict_child(ID, ARG_3_ID) :- _fch_op_{op_name}(ID, ARG_1_ID, ARG_2_ID, ARG_3_ID).")
            
        if allowed & Arity.VARIADIC:
            lines.append(f"_fch_op_{op_name}_variadic(ID, ARITY) :- _fch_flat(op_{op_name}_variadic(ID, ARITY)).")
            lines.append(f"_fch_op_{op_name}_arg(ID, INDEX, ARG) :- _fch_flat(op_{op_name}_arg(ID, INDEX, ARG)).")
            if op_name not in lazy_ops:
                lines.append(f"_fch_op_strict_child(ID, ARG) :- _fch_op_{op_name}_arg(ID, _, ARG).")

    return lines

def _generate_output():
    lines = []
    lines.extend(_build_header())

    for t in Type:
        if t == Type.FAIL:
            continue
        
        type_name = t.name.lower()
        const_name = f"_fch_type_{type_name}_id"
        
        lines.append(f"value(NAME, {type_name}, VALUE) :- ")
        lines.append(f"    _fch_static_expr_val(EXPR_ID, {const_name}, VALUE), ")
        lines.append(f"    _fch_var_def(NAME, EXPR_ID).\n")
        
        lines.append(f"value(NAME, {type_name}, VALUE) :- ")
        lines.append(f"    _fch_static_expr_val(EXPR_ID, {const_name}, VALUE), ")
        lines.append(f"    _fch_dynamic_var_def(NAME, EXPR_ID).\n")
        
        lines.append(f"value(NAME, {type_name}, VALUE) :- ")
        lines.append(f"    _fch_dynamic_expr_val(EXPR_ID, {const_name}, VALUE), ")
        lines.append(f"    _fch_var_def(NAME, EXPR_ID).\n")
        
        lines.append(f"value(NAME, {type_name}, VALUE) :- ")
        lines.append(f"    _fch_dynamic_expr_val(EXPR_ID, {const_name}, VALUE), ")
        lines.append(f"    _fch_dynamic_var_def(NAME, EXPR_ID).\n")

    lines.extend([
        "%% =============================================================================",
        "%% SET MEMBERS",
        "%% ============================================================================="
    ])
    
    for t in Type:
        if t in (Type.FAIL, Type.SET, Type.DICT):
            continue
            
        type_name = t.name.lower()
        const_name = f"_fch_type_{type_name}_id"
        
        lines.append(f"set_member(NAME, {type_name}, VAL) :- ")
        lines.append(f"    _fch_set_decl(NAME), ")
        lines.append(f"    _fch_set_member(NAME, {const_name}, VAL).\n")
        
        lines.append(f"set_member(VAR_NAME, {type_name}, VAL) :- ")
        lines.append(f"    _fch_var_def(VAR_NAME, TARGET_ID), ")
        lines.append(f"    _fch_set_member(TARGET_ID, {const_name}, VAL).\n")

    return lines