from typing import Literal

import clingo
import pytest

import constraint_handler
import tests.utils.testing as chut

ctrl_options = ["0", "--heuristic=Domain"]


def solve_with_clingo_statistics(
    name: str, engine: Literal["compile", "compile2", "ground", "propagator"] = "compile"
) -> dict:
    ctl = clingo.Control(["--stats=2"])
    constraint_handler.add_to_control(ctl)
    ctl.add(f"defaultEngine({engine}).")
    ctl.load(f"tests/correctness/{name}.lp")
    ctl.ground()

    result = ctl.solve()
    assert result.satisfiable

    return ctl.statistics


def run_test(name: str, engine: Literal["compile", "compile2", "ground", "propagator"], check_mode: bool = False):
    name = "tests/correctness/" + name
    engine_prg = f"defaultEngine({engine})."
    for test, extra_args in chut.build_expectations(name):
        options = ctrl_options + extra_args
        solver = chut.Solver(options, engine_prg, files=[name + ".lp"], propagator_check_only=check_mode)
        solver.solve(test)
        test.assert_()


core_tests = [
    "core/basic_assignments",
    "core/boolean_shortcut_optional_presence",
    "core/conditional_assign",
    "core/conj_bad_none_recovery",
    "core/custom_globals",
    "core/empty_set_execution",
    "core/empty_variadics",
    "core/integrity",
    "core/optional_absent_comparison_evaluation",
    "core/optional_absent_string_comparison_evaluation",
    "core/python_set_bool_brave",
    "core/reasoning_modes",
    "core/set_execution_input_alias",
    "core/set_interface_value_marker",
    "core/shared_optional_output_domains",
    "core/unprojected_optional_equality",
]

datatype_tests = [
    "datatype/bool/conj_disj",
    "datatype/bool/conj_disj_bad",
    "datatype/bool/conj_disj_mixed",
    "datatype/bool/conj_disj_none",
    "datatype/bool/conj_disj_variadic",
    "datatype/bool/derived_relations",
    "datatype/bool/equivalence_bad",
    "datatype/bool/evaluate",
    "datatype/bool/implication_bad",
    "datatype/bool/negation_logical_bad",
    "datatype/bool/negation_logical_basic",
    "datatype/bool/negation_logical_none",
    "datatype/bool/negation_strong_bad",
    "datatype/bool/negation_strong_basic",
    "datatype/bool/negation_strong_none",
    "datatype/bool/negation_weak_bad",
    "datatype/bool/negation_weak_basic",
    "datatype/bool/negation_weak_none",
    "datatype/float/division",
    "datatype/float/division_with_int",
    "datatype/float/equality_basic",
    "datatype/float/equality_cross_type",
    "datatype/float/extrema",
    "datatype/float/ordering_cross_type",
    "datatype/float/ordering_with_int",
    "datatype/float/rounding",
    "datatype/int/abs",
    "datatype/int/arithmetic_add_mul_basic",
    "datatype/int/arithmetic_sub_basic",
    "datatype/int/comparison",
    "datatype/int/division",
    "datatype/int/equality_compound_basic",
    "datatype/int/equality_cross_type",
    "datatype/int/extrema",
    "datatype/int/minus",
    "datatype/int/ordering_cross_type",
    "datatype/int/power",
    "datatype/strings",
]

engine_tests = [
    "engine/request",
    "engine/request_interaction",
    "engine/request_mixed_trig",
    "engine/request_mult",
    "engine/request_set_ref",
]

error_tests = [
    "error/recovery",
    "error/recovery_bool",
    "error/recovery_conditionals",
    "error/recovery_ensure",
]

execution_tests = [
    "execution/assert",
    "execution/change",
    "execution/conditional",
    "execution/conditional_assert",
    "execution/conditional_string_equality_single_model",
    "execution/implicit_variable",
    "execution/main_absolut",
    "execution/main_pyt",
    "execution/main_swap",
    "execution/optional_run",
    "execution/python_augassign",
    "execution/python_augassign_bad",
    "execution/python_augassign_float",
    "execution/python_augassign_types",
    "execution/python_integrity",
    "execution/python_integrity_should_be_ignored",
    "execution/python_list",
    "execution/python_set_empty_equality",
]

expression_tests = [
    "expression/bad_equality",
    "expression/lambda_recursive",
    "expression/lambda_zero_args",
    "expression/lambdas",
    "expression/python",
    "expression/python_extract/bad",
    "expression/python_extract/basic",
    "expression/python_extract/binding_leak",
    "expression/python_extract/dynamic",
    "expression/python_extract/set_input",
    "expression/python_extract/set_output",
    "expression/python_extract/set_projection",
    "expression/python_extract/static",
    "expression/python_extract/succeeds",
    "expression/python_extract/tuple_projection",
    "expression/python_multi_args",
    "expression/tuple",
    "expression/tuple_arity_mismatch",
    "expression/tuple_nested",
]

multimap_tests = [
    "multimap/basics",
    "multimap/equality",
    "multimap/executions",
    "multimap/main",
]

optimization_tests = [
    "optimization/multimap_bool",
    "optimization/multimap_float",
    "optimization/multimap_float_precision",
    "optimization/multimap_int",
    "optimization/multimap_labeled_values",
    "optimization/no_multimap_bool",
    "optimization/no_multimap_float",
    "optimization/no_multimap_float_precision",
    "optimization/no_multimap_int",
    "optimization/no_multimap_labeled_values",
    "optimization/optional_absent_linked_value",
    "optimization/preferences",
    "optimization/priority",
]

python_tests = [
    "python/bad",
    "python/dynamic",
    "python/set_input",
    "python/set_output",
    "python/static",
]

set_tests = [
    "set/comparisons",
    "set/diff_flat",
    "set/eq_neq_flat",
    "set/executions",
    "set/fold_bools",
    "set/from_domain",
    "set/inter_flat",
    "set/iterations",
    "set/length_flat",
    "set/manipulation_flat",
    "set/manipulations",
    "set/membership_decomposed",
    "set/membership_nested",
    "set/membership_python",
    "set/missing_declare_repair",
    "set/nested",
    "set/nondet_simple",
    "set/overapprox_boundaries",
    "set/same_val_multi_expr",
    "set/selfref",
    "set/set_in_set_notin",
    "set/set_make_flat",
    "set/subset_flat",
    "set/union_flat",
]

type_tests = [
    "type/bool/binary_ops",
    "type/bool/has_value",
    "type/bool/negation",
    "type/bool/with_none_binary",
    "type/bool/with_none_unary",
    "type/checking/composed",
    "type/checking/disabled_no_inference",
    "type/checking/invalid",
    "type/checking/membership_set_polymorphic",
    "type/checking/numeric",
    "type/checking/regression_guards",
    "type/checking/set",
    "type/checking/string_symbol",
    "type/multimap/membership",
    "type/multimap/operations",
    "type/python_extract/non_deterministic_python_type_inference",
    "type/python_extract/python_extract_type_inference",
    "type/python_extract/python_inference_type_warnings",
    "type/python_extract/type_inference_unknown_vs_no_type",
    "type/statement_python/inference_warnings",
    "type/statement_python/nondeterministic_inference",
    "type/statement_python/typing",
    "type/statement_python/unknown_vs_untyped",
    "type/statement_python/unknown_vs_untyped_nondeterministic",
    "type/variable/definition",
    "type/variable/fromFacts",
    "type/variadic/boolean_conj_disj",
    "type/variadic/boolean_leqv_lxor",
    "type/variadic/numeric",
    "type/warning/python",
    "type/warning/python_unsupported_type",
    "type/warning/type",
]

unit_tests = [
    "unit/bad_add",
    "unit/bad_concat",
    "unit/bad_eq",
    "unit/bad_float_div",
    "unit/bad_geq",
    "unit/bad_gt",
    "unit/bad_int_div",
    "unit/bad_leq",
    "unit/bad_leqv",
    "unit/bad_lt",
    "unit/bad_lxor",
    "unit/bad_max",
    "unit/bad_min",
    "unit/bad_mult",
    "unit/bad_neq",
    "unit/bad_sub",
    "unit/boolean_conj",
    "unit/boolean_default",
    "unit/boolean_disj",
    "unit/boolean_disj_none_bug",
    "unit/boolean_if",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/boolean_lxor",
    "unit/boolean_lxor_none_bug",
    "unit/equality_eq",
    "unit/equality_neq",
    "unit/float_add",
    "unit/float_eq",
    "unit/float_float_div",
    "unit/float_geq",
    "unit/float_gt",
    "unit/float_int_div",
    "unit/float_leq",
    "unit/float_lt",
    "unit/float_max",
    "unit/float_min",
    "unit/float_mult",
    "unit/float_neq",
    "unit/float_pow",
    "unit/float_sub",
    "unit/int_add",
    "unit/int_geq",
    "unit/int_gt",
    "unit/int_int_div",
    "unit/int_leq",
    "unit/int_lt",
    "unit/int_max",
    "unit/int_min",
    "unit/int_mult",
    "unit/int_pow",
    "unit/int_sub",
    "unit/nullary/boolean_conj",
    "unit/nullary/boolean_disj",
    "unit/nullary/boolean_leqv",
    "unit/nullary/boolean_lxor",
    "unit/nullary/float_add",
    "unit/nullary/float_mult",
    "unit/nullary/int_add",
    "unit/nullary/int_mult",
    "unit/nullary/python_python",
    "unit/nullary/python_pythonExtract",
    "unit/python_python",
    "unit/python_pythonExtract",
    "unit/set_diff",
    "unit/set_eq",
    "unit/set_inter",
    "unit/set_neq",
    "unit/set_set_isin",
    "unit/set_set_make",
    "unit/set_set_notin",
    "unit/set_subset",
    "unit/set_union",
    "unit/string_concat",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/tuple_eq",
    "unit/tuple_neq",
    "unit/unary/bad_abs",
    "unit/unary/bad_add",
    "unit/unary/bad_ceil",
    "unit/unary/bad_floor",
    "unit/unary/bad_hasValue",
    "unit/unary/bad_length",
    "unit/unary/bad_leqv",
    "unit/unary/bad_lnot",
    "unit/unary/bad_lxor",
    "unit/unary/bad_minus",
    "unit/unary/bad_snot",
    "unit/unary/bad_wnot",
    "unit/unary/boolean_hasValue",
    "unit/unary/boolean_leqv",
    "unit/unary/boolean_lnot",
    "unit/unary/boolean_lxor",
    "unit/unary/boolean_snot",
    "unit/unary/boolean_wnot",
    "unit/unary/float_abs",
    "unit/unary/float_add",
    "unit/unary/float_ceil",
    "unit/unary/float_floor",
    "unit/unary/float_minus",
    "unit/unary/float_mult",
    "unit/unary/int_abs",
    "unit/unary/int_add",
    "unit/unary/int_ceil",
    "unit/unary/int_floor",
    "unit/unary/int_minus",
    "unit/unary/int_mult",
    "unit/unary/set_length",
    "unit/unary/string_length",
]

variable_tests = [
    "variable/dynamic_type",
    "variable/flexible_domain",
    "variable/main",
    "variable/missing_domain_bad",
    "variable/parallel_declaration",
    "variable/same_val_multi_expr",
]

warning_tests = [
    "warning/bad",
    "warning/bad_interface",
    "warning/fake_forbid",
    "warning/ignore",
    "warning/python_extract/statement_error",
    "warning/python_extract/undeclared_variable",
    "warning/statement/control",
    "warning/statement/decl_lists",
    "warning/statement/python",
    "warning/statement/structure",
    "warning/syntax",
    "warning/variable_confusing_name",
    "warning/variable_reservedName",
    "warning/variable_undeclared",
    "warning/variable_undeclared_statement",
    "warning/variables",
]

base_tests = (
    core_tests
    + datatype_tests
    + engine_tests
    + error_tests
    + execution_tests
    + expression_tests
    + multimap_tests
    + optimization_tests
    + python_tests
    + set_tests
    + type_tests
    + unit_tests
    + variable_tests
    + warning_tests
)

other_tests = [
    "core/conditional_empty_set_linked_output",
    "core/empty_set_linked_output_execution",
    "core/optional_absent_conditional_set_output",
    "core/optional_set_empty_execution",
]

compile_skip: set[str] = set()
compile_xfail: set[str] = {
    "datatype/bool/conj_disj_mixed",
    "datatype/bool/conj_disj_none",
    "engine/request",
    "type/bool/with_none_binary",
    "type/bool/with_none_unary",
    "unit/bad_add",
    "unit/bad_concat",
    "unit/bad_float_div",
    "unit/bad_geq",
    "unit/bad_gt",
    "unit/bad_int_div",
    "unit/bad_leq",
    "unit/bad_leqv",
    "unit/bad_lt",
    "unit/bad_lxor",
    "unit/bad_max",
    "unit/bad_min",
    "unit/bad_mult",
    "unit/bad_sub",
    "unit/boolean_conj",
    "unit/boolean_disj",
    "unit/boolean_disj_none_bug",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/float_add",
    "unit/float_float_div",
    "unit/float_int_div",
    "unit/float_max",
    "unit/float_min",
    "unit/float_mult",
    "unit/float_pow",
    "unit/float_sub",
    "unit/int_add",
    "unit/int_int_div",
    "unit/int_max",
    "unit/int_min",
    "unit/int_mult",
    "unit/int_pow",
    "unit/int_sub",
    "unit/set_eq",
    "unit/set_neq",
    "unit/set_set_isin",
    "unit/set_set_notin",
    "unit/set_subset",
    "unit/set_union",
    "unit/string_concat",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/tuple_eq",
    "unit/tuple_neq",
    "unit/unary/bad_abs",
    "unit/unary/bad_add",
    "unit/unary/bad_ceil",
    "unit/unary/bad_floor",
    "unit/unary/bad_length",
    "unit/unary/bad_minus",
    "unit/unary/boolean_leqv",
    "unit/unary/boolean_lxor",
    "unit/unary/float_abs",
    "unit/unary/float_add",
    "unit/unary/float_ceil",
    "unit/unary/float_floor",
    "unit/unary/float_minus",
    "unit/unary/float_mult",
    "unit/unary/int_abs",
    "unit/unary/int_ceil",
    "unit/unary/int_floor",
    "unit/unary/int_minus",
    "unit/unary/string_length",
}

compile2_skip: set[str] = {
    "engine/request_mult",  # mixed engines
    "execution/python_integrity",  # non static input
    "variable/dynamic_type",  # non static input
}
compile2_xfail: set[str] = {
    "core/reasoning_modes",  # multimap
    "datatype/bool/conj_disj_mixed",
    "engine/request",
    "engine/request_set_ref",  # mixed engines?
    "expression/lambda_recursive",
    "expression/lambda_zero_args",
    "expression/lambdas",
    "expression/python_extract/basic",
    "expression/python_extract/set_input",
    "expression/python_extract/static",
    "multimap/basics",
    "multimap/equality",
    "multimap/executions",
    "multimap/main",
    "optimization/multimap_bool",
    "optimization/multimap_float",
    "optimization/multimap_float_precision",
    "optimization/multimap_int",
    "optimization/multimap_labeled_values",
    "optimization/priority",
    "set/fold_bools",
    "set/iterations",
    "set/manipulations",
    "set/membership_nested",
    "set/nested",
    "set/selfref",
    "type/bool/with_none_binary",
    "type/bool/with_none_unary",
    "type/checking/numeric",
    "type/multimap/operations",
    "unit/boolean_conj",
    "unit/boolean_disj",
    "unit/boolean_disj_none_bug",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/boolean_lxor",
    "unit/boolean_lxor_none_bug",
    "unit/float_max",
    "unit/float_min",
    "unit/float_pow",
    "unit/int_mult",
    "unit/python_pythonExtract",  # currently extracts not only variables, unsupported in compile2 engine
    "unit/string_concat",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/unary/bad_leqv",
    "unit/unary/bad_lxor",
    "unit/unary/set_length",
}
ground_skip: set[str] = {
    "core/python_set_bool_brave",
    "set/overapprox_boundaries",  ## too slow as it enumerates a lot of sets
    "set/selfref",
    "warning/python_extract/statement_error",
}
ground_xfail: set[str] = {
    "core/reasoning_modes",
    "core/set_execution_input_alias",
    "datatype/bool/conj_disj_mixed",
    "engine/request",
    "engine/request_set_ref",
    "expression/lambda_recursive",
    "expression/lambda_zero_args",
    "expression/lambdas",
    "multimap/basics",
    "multimap/equality",
    "multimap/executions",
    "multimap/main",
    "optimization/multimap_bool",
    "optimization/multimap_float",
    "optimization/multimap_float_precision",
    "optimization/multimap_int",
    "optimization/multimap_labeled_values",
    "optimization/priority",
    "set/fold_bools",
    "set/iterations",
    "type/bool/with_none_binary",
    "type/bool/with_none_unary",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/boolean_lxor",
    "unit/boolean_lxor_none_bug",
    "unit/set_diff",
    "unit/set_eq",
    "unit/set_inter",
    "unit/set_neq",
    "unit/set_set_isin",
    "unit/set_set_notin",
    "unit/set_subset",
    "unit/set_union",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/tuple_eq",
    "unit/tuple_neq",
    "unit/unary/bad_leqv",
    "unit/unary/bad_lxor",
    "unit/unary/set_length",
}

propagator_skip: set[str] = {
    "set/overapprox_boundaries",  ## too slow as it enumerates a lot of sets
    "warning/python_extract/statement_error",
}
propagator_xfail: set[str] = {
    "datatype/bool/conj_disj_mixed",
    "engine/request",
    "engine/request_mixed_trig",
    "expression/lambda_recursive",
    "expression/python_extract/set_output",
    "multimap/main",
    "optimization/preferences",
    "python/set_output",
    "set/fold_bools",
    "set/iterations",
    "set/selfref",
    "type/bool/with_none_binary",
    "type/bool/with_none_unary",
    "type/warning/python_unsupported_type",
    "warning/variables",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/boolean_lxor",
    "unit/boolean_lxor_none_bug",
    "unit/set_eq",
    "unit/set_neq",
    "unit/set_set_isin",
    "unit/set_set_notin",
    "unit/set_subset",
    "unit/set_union",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/unary/bad_leqv",
    "unit/unary/bad_lxor",
}

propagator_true_skip: set[str] = propagator_skip | set()
propagator_true_xfail: set[str] = propagator_xfail | set()

engine_test_configs: list[tuple[str, set[str], set[str], tuple[bool, ...]]] = [
    ("compile", compile_skip, compile_xfail, (False,)),
    ("compile2", compile2_skip, compile2_xfail, (False,)),
    ("ground", ground_skip, ground_xfail, (False,)),
    ("propagator", propagator_skip, propagator_xfail, (False,)),
    ("propagator", propagator_true_skip, propagator_true_xfail, (True,)),
]


def param_marks(
    name: str,
    skip: set[str],
    xfail: set[str],
    engine: str,
):
    """Return pytest marks for a test name under a specific engine context."""
    if name in skip:
        return [pytest.mark.skip(reason=f"skipped in {engine} engine")]
    if name in xfail:
        return [pytest.mark.xfail(reason=f"known failure in {engine} engine")]
    return []


@pytest.mark.parametrize(
    ["name", "engine", "check_mode"],
    [
        pytest.param(
            name,
            engine,
            check_mode,
            marks=param_marks(name, skip, xfail, engine),
        )
        for engine, skip, xfail, check_modes in engine_test_configs
        for check_mode in check_modes
        for name in base_tests
    ],
)
def test_engine(name: str, engine: Literal["compile", "compile2", "ground", "propagator"], check_mode: bool):
    run_test(name, engine, check_mode)


choice_statistics_skip: set[str] = {
    "core/boolean_shortcut_optional_presence",
    "core/empty_set_execution",
    "core/optional_set_empty_execution",
    "core/python_set_bool_brave",
    "core/set_interface_value_marker",
    "core/shared_optional_output_domains",
    "core/unprojected_optional_equality",
    "execution/conditional_string_equality_single_model",
    "expression/python_extract/dynamic",
    "expression/python_extract/succeeds",
    "optimization/optional_absent_linked_value",
    "python/dynamic",
    "warning/python_extract/statement_error",
    "unit/bad_add",
    "unit/bad_concat",
    "unit/bad_eq",
    "unit/bad_float_div",
    "unit/bad_geq",
    "unit/bad_gt",
    "unit/bad_int_div",
    "unit/bad_leq",
    "unit/bad_leqv",
    "unit/bad_lt",
    "unit/bad_lxor",
    "unit/bad_max",
    "unit/bad_min",
    "unit/bad_mult",
    "unit/bad_neq",
    "unit/bad_sub",
    "unit/boolean_conj",
    "unit/boolean_default",
    "unit/boolean_disj",
    "unit/boolean_disj_none_bug",
    "unit/boolean_if",
    "unit/boolean_ite",
    "unit/boolean_leqv",
    "unit/boolean_leqv_none_bug",
    "unit/boolean_limp",
    "unit/boolean_limp_none_bug",
    "unit/boolean_lxor",
    "unit/boolean_lxor_none_bug",
    "unit/equality_eq",
    "unit/equality_neq",
    "unit/float_add",
    "unit/float_eq",
    "unit/float_float_div",
    "unit/float_geq",
    "unit/float_gt",
    "unit/float_int_div",
    "unit/float_leq",
    "unit/float_lt",
    "unit/float_max",
    "unit/float_min",
    "unit/float_mult",
    "unit/float_neq",
    "unit/float_pow",
    "unit/float_sub",
    "unit/int_add",
    "unit/int_geq",
    "unit/int_gt",
    "unit/int_int_div",
    "unit/int_leq",
    "unit/int_lt",
    "unit/int_max",
    "unit/int_min",
    "unit/int_mult",
    "unit/int_pow",
    "unit/int_sub",
    "unit/nullary/boolean_conj",
    "unit/nullary/boolean_disj",
    "unit/nullary/boolean_leqv",
    "unit/nullary/boolean_lxor",
    "unit/nullary/float_add",
    "unit/nullary/float_mult",
    "unit/nullary/int_add",
    "unit/nullary/int_mult",
    "unit/nullary/python_python",
    "unit/nullary/python_pythonExtract",
    "unit/python_python",
    "unit/python_pythonExtract",
    "unit/set_diff",
    "unit/set_eq",
    "unit/set_inter",
    "unit/set_neq",
    "unit/set_set_isin",
    "unit/set_set_make",
    "unit/set_set_notin",
    "unit/set_subset",
    "unit/set_union",
    "unit/string_concat",
    "unit/string_geq",
    "unit/string_gt",
    "unit/string_leq",
    "unit/string_lt",
    "unit/symbol_geq",
    "unit/symbol_gt",
    "unit/symbol_leq",
    "unit/symbol_lt",
    "unit/tuple_eq",
    "unit/tuple_neq",
    "unit/unary/bad_abs",
    "unit/unary/bad_add",
    "unit/unary/bad_ceil",
    "unit/unary/bad_floor",
    "unit/unary/bad_hasValue",
    "unit/unary/bad_length",
    "unit/unary/bad_leqv",
    "unit/unary/bad_lnot",
    "unit/unary/bad_lxor",
    "unit/unary/bad_minus",
    "unit/unary/bad_snot",
    "unit/unary/bad_wnot",
    "unit/unary/boolean_hasValue",
    "unit/unary/boolean_leqv",
    "unit/unary/boolean_lnot",
    "unit/unary/boolean_lxor",
    "unit/unary/boolean_snot",
    "unit/unary/boolean_wnot",
    "unit/unary/float_abs",
    "unit/unary/float_add",
    "unit/unary/float_ceil",
    "unit/unary/float_floor",
    "unit/unary/float_minus",
    "unit/unary/float_mult",
    "unit/unary/int_abs",
    "unit/unary/int_add",
    "unit/unary/int_ceil",
    "unit/unary/int_floor",
    "unit/unary/int_minus",
    "unit/unary/int_mult",
    "unit/unary/set_length",
    "unit/unary/string_length",
}
choice_statistics_xfail: set[str] = {
    "core/conditional_assign",
    "core/integrity",
    "core/reasoning_modes",
    "datatype/bool/derived_relations",
    "datatype/bool/equivalence_bad",
    "datatype/bool/evaluate",
    "datatype/bool/implication_bad",
    "datatype/strings",
    "error/recovery_ensure",
    "execution/assert",
    "execution/change",
    "execution/conditional",
    "execution/main_absolut",
    "execution/main_swap",
    "execution/optional_run",
    "execution/python_integrity",
    "expression/bad_equality",
    "optimization/multimap_bool",
    "optimization/multimap_float",
    "optimization/multimap_float_precision",
    "optimization/multimap_int",
    "optimization/multimap_labeled_values",
    "optimization/no_multimap_bool",
    "optimization/no_multimap_float",
    "optimization/no_multimap_float_precision",
    "optimization/no_multimap_int",
    "optimization/no_multimap_labeled_values",
    "optimization/preferences",
    "optimization/priority",
    "set/diff_flat",
    "set/eq_neq_flat",
    "set/from_domain",
    "set/inter_flat",
    "set/length_flat",
    "set/membership_decomposed",
    "set/membership_python",
    "set/nondet_simple",
    "set/overapprox_boundaries",
    "set/same_val_multi_expr",
    "set/selfref",
    "set/set_in_set_notin",
    "set/set_make_flat",
    "set/subset_flat",
    "set/union_flat",
    "type/checking/invalid",
    "type/checking/membership_set_polymorphic",
    "type/checking/regression_guards",
    "type/multimap/membership",
    "type/python_extract/non_deterministic_python_type_inference",
    "type/statement_python/nondeterministic_inference",
    "type/statement_python/unknown_vs_untyped_nondeterministic",
    "type/warning/python",
    "type/warning/type",
    "variable/dynamic_type",
    "variable/flexible_domain",
    "variable/main",
    "variable/parallel_declaration",
    "variable/same_val_multi_expr",
    "warning/bad",
    "warning/fake_forbid",
    "warning/variable_reservedName",
    "warning/variable_undeclared",
    "warning/variables",
}


@pytest.mark.parametrize(
    "name",
    [
        pytest.param(
            name,
            marks=param_marks(name, choice_statistics_skip, choice_statistics_xfail, "compile statistics choices"),
        )
        for name in base_tests
    ],
)
def test_compile_statistics_have_zero_choices(name: str):
    statistics = solve_with_clingo_statistics(name)
    assert statistics["solving"]["solvers"]["choices"] == 0.0


tightness_statistics_skip: set[str] = {"core/python_set_bool_brave"}
tightness_statistics_xfail: set[str] = {
    "optimization/multimap_bool",
    "optimization/multimap_float",
    "optimization/multimap_float_precision",
    "optimization/multimap_int",
    "optimization/multimap_labeled_values",
    "optimization/priority",
    "variable/dynamic_type",
}


@pytest.mark.parametrize(
    "name",
    [
        pytest.param(
            name,
            marks=param_marks(
                name, tightness_statistics_skip, tightness_statistics_xfail, "compile statistics tightness"
            ),
        )
        for name in base_tests
    ],
)
def test_compile_statistics_are_tight(name: str):
    statistics = solve_with_clingo_statistics(name)
    assert statistics["problem"]["lp"]["sccs"] == 0.0
